---
title: "Predictive Analysis for Breast Cancer"
author: "hg420@scarletmail.rutgers.edu"
date: "2024-02-12"
output: html_document
---

Individual Project - Predictive Analysis for Breast Cancer
 "Dataset link: https://www.kaggle.com/datasets/yasserh/breast-cancer-dataset"

"1. Ask an important question you want answered (1 at least) : 2 Points"
"a) What methods can be employed to forecast whether a breast tumor is malignant or benign?"
"b) How can we estimate the average radius of breast cancer tumor lobes?"


"2. Answer why this question(s) is/are important to you: 2 Points"
"Recognizing whether a breast tumor is malignant or benign is essential for selecting suitable treatment strategies and enhancing patient prognosis"
"Calculating the average radius of breast cancer tumor lobes can offer valuable understanding into tumor features, assisting in diagnosis and treatment choices"


"3. Find and collect data (need one dependent variable and more than 3 dependent variables): 2 Points"
"Dependent variable: Diagnosis (Malignant or Benign)"
"Independent variables: Mean radius, Mean texture, Mean perimeter, Mean area, Mean smoothness, Mean compactness, Mean concavity, Mean concave points, Mean symmetry, Mean fractal dimension"


"4. Describe your data (create a data dictionary): 4 Points"
"ID : Unique identifier for each instance or observation (Data type: Numeric)"
"Diagnosis: The target variable indicating whether the breast tumor is malignant (M) or benign (B) (Data type: Text)"
"Radius: The mean distance from the center to points on the perimeter (Data type: Numeric)"
"Texture: The standard deviation of gray-scale values (Data type: Numeric)"
"Perimeter: The mean perimeter of the cell nucleus (Data type: Numeric)"
"Area: The mean area of the cell nucleus (Data type: Numeric)"
"Smoothness: The local variation in radius lengths (Data type: Numeric)"
"Compactness: The measure of compactness calculated (Data type: Numeric)"
"Concavity: The severity of concave portions of the contour (Data type: Numeric)"
"Concave points: The number of concave portions of the contour (Data type: Numeric)"
"Symmetry: A measure of symmetry (Data type: Numeric)"
"Fractal dimension: A measure related to the "coastline approximation"-1 (Data type: Numeric)"



